// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniqueString.Infrastructure.DAL.Data;

namespace UniqueString.Infrastructure.DAL.Migrations
{
    [DbContext(typeof(UniqueStringDBContext))]
    [Migration("20210804143813_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UniqueString.Core.Entities.UniqueStringEntity", b =>
                {
                    b.Property<string>("Text")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Text");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("UniqueString");
                });
#pragma warning restore 612, 618
        }
    }
}
